/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed": "#001e2b",
                "on-secondary": "#ffffff",
                "primary-fixed": "#dde1ff",
                "tertiary-fixed": "#c2e8ff",
                "tertiary": "#005471",
                "on-primary": "#ffffff",
                "secondary": "#a04100",
                "surface-variant": "#e2e2e5",
                "on-surface": "#1a1c1e",
                "on-secondary-fixed": "#351000",
                "surface-container-highest": "#e2e2e5",
                "on-error": "#ffffff",
                "on-tertiary": "#ffffff",
                "secondary-fixed-dim": "#ffb693",
                "error": "#ba1a1a",
                "on-primary-fixed": "#001452",
                "surface-bright": "#f9f9fc",
                "on-secondary-fixed-variant": "#7a3000",
                "primary-fixed-dim": "#b7c4ff",
                "error-container": "#ffdad6",
                "surface": "#f9f9fc",
                "surface-container-low": "#f3f3f6",
                "outline-variant": "#c3c5d9",
                "inverse-on-surface": "#f0f0f3",
                "outline": "#737688",
                "background": "#f9f9fc",
                "inverse-primary": "#b7c4ff",
                "secondary-fixed": "#ffdbcc",
                "secondary-container": "#fe6b00",
                "on-error-container": "#93000a",
                "tertiary-fixed-dim": "#75d1ff",
                "tertiary-container": "#006e92",
                "on-tertiary-container": "#c6eaff",
                "on-primary-container": "#dfe3ff",
                "on-secondary-container": "#572000",
                "surface-container-high": "#e8e8ea",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#0038b6",
                "on-background": "#1a1c1e",
                "primary-container": "#0052ff",
                "surface-dim": "#dadadc",
                "surface-tint": "#004ced",
                "on-tertiary-fixed-variant": "#004d67",
                "on-surface-variant": "#434656",
                "primary": "#003ec7",
                "surface-container": "#eeeef0",
                "inverse-surface": "#2f3133",
            },
            fontFamily: {
                jakarta: ["Plus Jakarta Sans", "sans-serif"],
                inter: ["Inter", "sans-serif"],
            },
        },
    },
    plugins: [],
};