/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdbcc",
        "on-primary-fixed": "#001848",
        "surface-container-high": "#e7e8ea",
        "surface-bright": "#f8f9fb",
        "on-secondary-container": "#572000",
        "inverse-surface": "#2e3132",
        "surface-variant": "#e1e2e4",
        "secondary": "#a04100",
        "on-surface-variant": "#434654",
        "surface-dim": "#d9dadc",
        "primary-fixed": "#dae2ff",
        "primary-container": "#0052cc",
        "outline-variant": "#c3c6d6",
        "tertiary-fixed": "#adecff",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#70e2ff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b2c5ff",
        "tertiary-container": "#006476",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb693",
        "surface-container-highest": "#e1e2e4",
        "background": "#f8f9fb",
        "surface-container-low": "#f3f4f6",
        "tertiary": "#004b58",
        "outline": "#737685",
        "inverse-primary": "#b2c5ff",
        "on-tertiary-fixed-variant": "#004e5d",
        "surface-tint": "#0c56d0",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#c4d2ff",
        "tertiary-fixed-dim": "#5dd6f3",
        "inverse-on-surface": "#f0f1f3",
        "secondary-container": "#fe6b00",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#0040a2",
        "surface": "#f8f9fb",
        "surface-container": "#edeef0",
        "on-secondary-fixed-variant": "#7a3000",
        "on-primary": "#ffffff",
        "primary": "#003d9b",
        "on-tertiary-fixed": "#001f26",
        "on-secondary-fixed": "#351000",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "xs": "4px",
        "margin-mobile": "16px",
        "sm": "8px",
        "margin-desktop": "64px",
        "xl": "32px",
        "md": "16px",
        "lg": "24px",
        "base": "4px",
        "gutter": "24px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
