<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Xc thc OTP_agreeTerms</name>
   <tag></tag>
   <elementGuidId>83d9061c-4096-462b-a814-3adca10fe9bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#agreeTerms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='agreeTerms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Bằng cách đăng ký, tôi đồng ý với Điều khoản dịch vụ và Chính sách bảo mật của Chip3Chip.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdb46740-8fb6-441d-9769-089a8aed5db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 rounded text-[#003d9b] focus:ring-[#003d9b]</value>
      <webElementGuid>17389434-aaa5-41bf-816d-1fe3051962ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>agreeTerms</value>
      <webElementGuid>5d446dd9-cafd-4374-9b73-4ad26d6ef2a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7c408c06-1448-4028-a0a4-4ea59b7d4318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;agreeTerms&quot;)</value>
      <webElementGuid>8202b9e1-fac1-4b62-a8b7-5a6f4e519d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='agreeTerms']</value>
      <webElementGuid>eac29aaf-db82-4038-b9bc-38f151c7a6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[7]/input</value>
      <webElementGuid>c1ec26bb-d579-4189-80df-50b135054124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>3d8ac57e-ada4-494d-9b3f-27137f7a7d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'agreeTerms' and @type = 'checkbox']</value>
      <webElementGuid>ae4bde54-3cc6-40cb-8f85-b9ec596d28ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
