<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_calendar_today</name>
   <tag></tag>
   <elementGuidId>066b0c7c-58c7-4195-9d55-adf875ecd94c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/div[2]/form/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;calendar_today&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2cada95a-d38c-4cf8-8749-767cea8ccdb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-[#434654] text-[20px]</value>
      <webElementGuid>e5febe0c-6000-4121-b907-2def860573bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>calendar_today</value>
      <webElementGuid>4fc0a245-eba9-4d91-95fe-ee3e9a871a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-[#f8f9fb] text-[#191c1e] min-h-screen flex flex-col font-sans&quot;]/main[@class=&quot;flex-grow flex items-center justify-center pt-24 pb-12 px-4&quot;]/div[@class=&quot;max-w-6xl w-full grid md:grid-cols-2 bg-white rounded-xl overflow-hidden shadow-lg border border-[#c3c6d6]&quot;]/div[@class=&quot;p-6 md:p-8 flex flex-col&quot;]/form[@class=&quot;space-y-4&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 gap-4&quot;]/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;relative&quot;]/span[@class=&quot;material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-[#434654] text-[20px]&quot;]</value>
      <webElementGuid>bafc7e42-d481-46b8-af19-2ee32cbd397a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div[2]/form/div[2]/div/div/span</value>
      <webElementGuid>c45fe6f9-c6ed-4c0e-b1c5-5cf541fd47a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày tháng năm sinh'])[1]/following::span[1]</value>
      <webElementGuid>8c3a0011-0392-4ae3-b3ea-6f82701f7e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='person'])[1]/following::span[1]</value>
      <webElementGuid>19ebf03e-b20a-47a1-84c4-0f0394558381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số điện thoại'])[1]/preceding::span[1]</value>
      <webElementGuid>9c5e17ec-7e78-4edf-a718-932aec2599de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='call'])[1]/preceding::span[1]</value>
      <webElementGuid>ecf7e7d6-bbbc-47e9-98ce-aac5a35be628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='calendar_today']/parent::*</value>
      <webElementGuid>834cacdb-c5ec-499d-917e-15eb3a6a296c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>8c459a5e-bd5a-48f9-8583-7b8de415d828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'calendar_today' or . = 'calendar_today')]</value>
      <webElementGuid>eff58a30-f0d5-47c2-bcb0-d6c1c588b3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
