<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ThemDiaDiem</name>
   <tag></tag>
   <elementGuidId>d1599a0a-6a7e-4c87-933a-0951a49ed814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^location_onCác địa điểm ghé thăm \(1\)\+ Thêm địa điểm$/ >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30229d38-bd92-4300-a78d-3b642b1cc155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e2cde1a-9d75-4aed-ad1d-8002429be6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[10px] text-primary font-semibold hover:underline flex items-center gap-0.5</value>
      <webElementGuid>942c82a5-270e-47fd-9abd-786a162e1f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+ Thêm địa điểm</value>
      <webElementGuid>0df67cb8-d1b0-4e45-aa8d-d2f3a1260b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-background text-on-background min-h-screen flex flex-col&quot;]/main[@class=&quot;flex-grow pt-20 pb-s-xl px-s-margin-mobile md:px-s-margin-desktop max-w-[1440px] mx-auto w-full&quot;]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-gutter items-start&quot;]/div[@class=&quot;space-y-lg&quot;]/section[@class=&quot;bg-white rounded-xl border border-outline-variant/30 shadow-sm p-s-xl&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;border border-outline-variant/30 rounded-xl overflow-hidden shadow-sm bg-white&quot;]/div[@class=&quot;p-5 space-y-4&quot;]/div[@class=&quot;border-t border-outline-variant/20 pt-4&quot;]/div[@class=&quot;flex items-center justify-between mb-3&quot;]/button[@class=&quot;text-[10px] text-primary font-semibold hover:underline flex items-center gap-0.5&quot;]</value>
      <webElementGuid>c2f56e48-86b1-4d17-8180-588905839271</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>5be5cb89-6380-4388-915c-0c5333c6f531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section[4]/div[2]/div/div[2]/div[2]/div/button</value>
      <webElementGuid>0468b474-3100-4e65-9121-ee7ac4bbd728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='location_on'])[1]/following::button[1]</value>
      <webElementGuid>a26db9fc-00e4-40a9-8e2a-9616c43242eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/preceding::button[1]</value>
      <webElementGuid>ea8413d3-aadb-4326-a413-414daad4831d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/preceding::button[1]</value>
      <webElementGuid>7d559669-64fe-40b8-b27f-f64b26c40e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ Thêm địa điểm']/parent::*</value>
      <webElementGuid>9e2893f2-8c44-480a-825f-6d36cf54b323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/button</value>
      <webElementGuid>c9422e9e-2b66-440b-9c1c-dc95e0884b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '+ Thêm địa điểm' or . = '+ Thêm địa điểm')]</value>
      <webElementGuid>798eb93c-4222-4d60-8e76-61194c22243d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
