<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__TenTour</name>
   <tag></tag>
   <elementGuidId>2f4ae0ab-2508-4b85-9524-592545731072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tour-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tour-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ví dụ: Khám phá Vẻ đẹp Tiềm ẩn của Hà Giang&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7902a85d-baab-499e-891a-80e2e7b6b460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tour-title</value>
      <webElementGuid>9c013f62-0c85-4c46-81de-5d672b4ccba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ví dụ: Khám phá Vẻ đẹp Tiềm ẩn của Hà Giang</value>
      <webElementGuid>9074cb67-b598-46f4-aff3-82ec538aa359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 rounded-lg border border-outline-variant text-sm focus:outline-none focus:ring-2 focus:ring-primary/30</value>
      <webElementGuid>bfb18fd3-102e-4646-ba97-5d114e999f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4582bd45-2c7b-40d4-bb96-6ac56a235037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tour-title&quot;)</value>
      <webElementGuid>45eda276-53b0-4e99-b5f2-e32bc0d87093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tour-title']</value>
      <webElementGuid>da9fa47d-4fba-44f9-ac69-d6fa679f8951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section/div[2]/div/input</value>
      <webElementGuid>33c413d5-782a-4140-8fff-e61df0d27541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e648ec55-23d9-4d0b-84eb-297533c14edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tour-title' and @placeholder = 'Ví dụ: Khám phá Vẻ đẹp Tiềm ẩn của Hà Giang' and @type = 'text']</value>
      <webElementGuid>01d8dc95-d419-44ec-9e31-1edf077e32fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
