<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__diemDen</name>
   <tag></tag>
   <elementGuidId>aa500fe2-8485-49fe-bd64-b7c7dfd2a392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tour-destination']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tour-destination</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ví dụ: Hà Giang, Vịnh Hạ Long...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a41eef61-26e9-4405-8e21-e86bb1d03c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tour-destination</value>
      <webElementGuid>929acc21-f742-49f1-8e50-8c9feda22bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ví dụ: Hà Giang, Vịnh Hạ Long...</value>
      <webElementGuid>7d94f20c-172b-4984-8141-5e38eae42a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 rounded-lg border border-outline-variant text-sm focus:outline-none focus:ring-2 focus:ring-primary/30</value>
      <webElementGuid>a792c4b8-1e89-4a86-aa03-08e0b53bc43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5afc18f7-021b-448b-8870-9c0c69c82df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tour-destination&quot;)</value>
      <webElementGuid>de296229-bcdd-45bc-8975-3811a123bf50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tour-destination']</value>
      <webElementGuid>f00245d6-9a87-448c-b66d-8cec1558da45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>d4eca103-f1da-4766-a98b-671c04aa31cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>4327247b-db5c-4ce6-962e-b6494c3360d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tour-destination' and @placeholder = 'Ví dụ: Hà Giang, Vịnh Hạ Long...' and @type = 'text']</value>
      <webElementGuid>dfa1b41d-65a3-463e-84a2-068d52dbfe71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
