<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TenDia</name>
   <tag></tag>
   <elementGuidId>74915c76-e67e-4b0f-a8ad-619616e2ac79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='day-title-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Tên địa điểm (Cột cờ Lũng Cú...)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5999be99-1692-4a16-8c35-4e468ccfb9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tên địa điểm (Cột cờ Lũng Cú...)</value>
      <webElementGuid>0bfbdead-ee4d-4df5-bbe5-6344b9b51f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-2.5 py-1.5 border border-outline-variant rounded text-xs focus:outline-none</value>
      <webElementGuid>79cc2a39-e14c-4a0a-a43f-c44be9c3095c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7fdda40e-5a3c-4871-950e-7dc4375f6c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;bg-background text-on-background min-h-screen flex flex-col&quot;]/main[@class=&quot;flex-grow pt-20 pb-s-xl px-s-margin-mobile md:px-s-margin-desktop max-w-[1440px] mx-auto w-full&quot;]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-gutter items-start&quot;]/div[@class=&quot;space-y-lg&quot;]/section[@class=&quot;bg-white rounded-xl border border-outline-variant/30 shadow-sm p-s-xl&quot;]/div[@class=&quot;space-y-6&quot;]/div[@class=&quot;border border-outline-variant/30 rounded-xl overflow-hidden shadow-sm bg-white&quot;]/div[@class=&quot;p-5 space-y-4&quot;]/div[@class=&quot;border-t border-outline-variant/20 pt-4&quot;]/div[@class=&quot;space-y-3&quot;]/div[@class=&quot;p-3 bg-surface-container-lowest border border-outline-variant/30 rounded-lg grid grid-cols-1 md:grid-cols-[1fr_120px_120px_60px_auto] gap-2 items-center&quot;]/input[@class=&quot;px-2.5 py-1.5 border border-outline-variant rounded text-xs focus:outline-none&quot;]</value>
      <webElementGuid>7530320e-c1a8-47d7-8c30-faa8e3fc0e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[15]</value>
      <webElementGuid>e077be87-2d92-4b47-9d82-7e1ab47cc690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section[4]/div[2]/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>57debbe6-46a6-48fc-9e42-6623977b08dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>b914c1bd-c7c7-4c6c-a708-e117a89514db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tên địa điểm (Cột cờ Lũng Cú...)' and @type = 'text']</value>
      <webElementGuid>b176ebad-e946-4af7-b15e-a7559c41e735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
