<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__KinhDo</name>
   <tag></tag>
   <elementGuidId>450a17d3-08fd-44f6-affc-1d28f72a80d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loc-lng-0-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loc-lng-0-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Kinh độ (Lng)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>473ed7c4-e699-4821-b8f0-ab1f92c1efee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loc-lng-0-0</value>
      <webElementGuid>265cb714-e714-46b2-a177-3c753149be51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>ec5fb47c-bf9f-4949-b20d-beea1409f19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kinh độ (Lng)</value>
      <webElementGuid>902dee46-a946-48a4-b626-fda7f8623941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2.5 py-1.5 border border-outline-variant rounded text-xs focus:outline-none pr-4</value>
      <webElementGuid>32bcd52e-2e60-4ea6-9c5c-fb882323d683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b72d3cd9-9658-47cf-b187-75af76764b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loc-lng-0-0&quot;)</value>
      <webElementGuid>d7df58aa-a79b-4187-9076-84e15b6cb12b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loc-lng-0-0']</value>
      <webElementGuid>1f0c1c76-922c-49ec-895e-48d0967417c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section[4]/div[2]/div/div[2]/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>f5e1519d-c255-461f-96db-f801534f6ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>62197f84-f172-40cb-a50c-f49f19d91913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loc-lng-0-0' and @placeholder = 'Kinh độ (Lng)' and @type = 'number']</value>
      <webElementGuid>222d233c-6480-4045-a819-c1868ba8aa1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
