<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ViDo</name>
   <tag></tag>
   <elementGuidId>df11357d-d37b-4692-9641-a8c047581af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tour-base-price']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loc-lat-0-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Vĩ độ (Lat)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40940e8d-759b-4a9a-bfbe-3d83ab14e6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loc-lat-0-0</value>
      <webElementGuid>678c549f-a962-4e54-8f95-242fbbb34ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>9bf3b7cf-f700-4864-bcbd-2e94f913fb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vĩ độ (Lat)</value>
      <webElementGuid>fd9a7c64-62cc-4b88-ae48-99e5db1bd3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-2.5 py-1.5 border border-outline-variant rounded text-xs focus:outline-none pr-4</value>
      <webElementGuid>1b8fa11e-2fec-41e3-afbd-4d497800286b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>20fdfaf7-6838-41b6-9752-d7cfcda2e0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loc-lat-0-0&quot;)</value>
      <webElementGuid>a4982293-af81-421f-9f78-8c7bcf302eec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loc-lat-0-0']</value>
      <webElementGuid>7b9408ce-9a26-4e92-8aab-e5f90812978c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section[4]/div[2]/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>33fe8652-7eaf-4e77-a1a4-972b1d661081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>1646da82-cfea-4c3f-889f-16159f0bd79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'loc-lat-0-0' and @placeholder = 'Vĩ độ (Lat)' and @type = 'number']</value>
      <webElementGuid>3b581a16-d4f5-4f4d-8e25-8bb804e75dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
