<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DiemXuatPhat</name>
   <tag></tag>
   <elementGuidId>81f0a65c-a3e7-42cf-a3b8-75f36ecae4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tour-departure-location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tour-departure-location</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ví dụ: Hà Nội, TP. Hồ Chí Minh...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e042359-e7aa-4172-ad4e-cf7991cf73da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tour-departure-location</value>
      <webElementGuid>a222773c-da9d-4219-85af-729c5c85ec7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ví dụ: Hà Nội, TP. Hồ Chí Minh...</value>
      <webElementGuid>9d4323de-465e-4a03-8f4f-78886b52b2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 rounded-lg border border-outline-variant text-sm focus:outline-none focus:ring-2 focus:ring-primary/30</value>
      <webElementGuid>5b848b41-3d47-4ffb-8f10-40a61b188fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9f8ac16-63bd-4098-9559-84f92d3bbbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tour-departure-location&quot;)</value>
      <webElementGuid>b065fcab-8620-4bc2-8245-69762b9ce9a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tour-departure-location']</value>
      <webElementGuid>b3479a79-f17c-4e15-bd7f-daaab9cf524a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section/div[2]/div[3]/div/input</value>
      <webElementGuid>271bbfc6-6129-44da-97e0-6416e1a28bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3a04406c-8457-498c-a268-0c7111d585d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tour-departure-location' and @placeholder = 'Ví dụ: Hà Nội, TP. Hồ Chí Minh...' and @type = 'text']</value>
      <webElementGuid>e27800b8-d356-48bf-8411-b4bec401798b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
