<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Gia</name>
   <tag></tag>
   <elementGuidId>2bdfcddb-2992-47c3-b25c-6b889b5defcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='schedule-price-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#schedule-price-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Giá riêng&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1de08fd0-f590-44ed-a362-6f88c0199c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>schedule-price-0</value>
      <webElementGuid>80d315a3-ff1d-44b6-9b27-8b02bfaa794e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Giá riêng</value>
      <webElementGuid>6272889f-bc35-47fc-b92e-5e5003a15454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border border-outline-variant rounded-lg text-xs focus:outline-none</value>
      <webElementGuid>fd65c420-ecb9-4870-bd3e-c81ae8708224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>20a30486-0b8b-4765-962b-0a327ef6f21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedule-price-0&quot;)</value>
      <webElementGuid>eff3efe4-5e19-4517-a5c2-1f7ee03abb50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='schedule-price-0']</value>
      <webElementGuid>16dd4b26-7f37-4489-9241-8b35d84210a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section[3]/div[2]/div/div[3]/input</value>
      <webElementGuid>2a0d3b06-e5db-4b49-a20e-ea1b2f320621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[2]/div/div[3]/input</value>
      <webElementGuid>19b35fa3-0a84-414c-8f23-71f17732e769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'schedule-price-0' and @placeholder = 'Giá riêng' and @type = 'number']</value>
      <webElementGuid>431fe85d-d144-4142-a6b2-67ae6fdcdbec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
