<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ThemAnhDaiDien</name>
   <tag></tag>
   <elementGuidId>6631784c-2c2b-4941-b814-5794deea5c64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tour-thumbnail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tour-thumbnail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tour-thumbnail</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb0a21fc-4a12-4d4e-92f2-cc07cfddcace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tour-thumbnail</value>
      <webElementGuid>9bd9f545-e4c1-4ce6-b510-f6d2dc026016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>a89cf7c4-f562-4a6f-94c7-4e5e4b3cc7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 opacity-0 cursor-pointer</value>
      <webElementGuid>7518c1a8-2659-4bd8-91aa-162953b63756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>388305eb-89e9-4bd8-8ab6-fb6be600a842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tour-thumbnail&quot;)</value>
      <webElementGuid>69d8bef6-415d-416a-84e2-08b16e2cc882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tour-thumbnail']</value>
      <webElementGuid>46df3377-45bf-4001-9871-d9ba637f4c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section[5]/div[2]/div/div/input</value>
      <webElementGuid>743baf34-ea03-41a1-90df-156fddd639b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div[2]/div/div/input</value>
      <webElementGuid>f6683375-abf4-42fa-a4c6-050d6d58a681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tour-thumbnail' and @type = 'file']</value>
      <webElementGuid>7ba8dcf5-5e8f-45bd-9e75-d1c9ebe48dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
