<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NgayDi</name>
   <tag></tag>
   <elementGuidId>f130b0c8-df32-4f93-aca8-e2c9ddd56211</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='schedule-dep-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#schedule-dep-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#schedule-dep-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>096570b8-f617-4a8f-82fb-ab4caa8883b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>schedule-dep-0</value>
      <webElementGuid>7bb10d7b-a048-493e-b10d-7fbdb2a26cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border border-outline-variant rounded-lg text-xs focus:outline-none</value>
      <webElementGuid>2137c98d-bf69-4b94-8c45-05fe70c8c2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>8579da80-4535-42da-86cd-2f4eb8738741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedule-dep-0&quot;)</value>
      <webElementGuid>c685ad67-a8d9-48ec-a2dc-672cbb7aa56c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='schedule-dep-0']</value>
      <webElementGuid>381a3d4f-6e27-4875-8e4c-ae3f0705dfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section[3]/div[2]/div/div/input</value>
      <webElementGuid>82c4f1d6-1152-4295-be7f-06322b991f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[2]/div/div/input</value>
      <webElementGuid>86287214-10e3-4aeb-a4f8-fd74d9c379c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'schedule-dep-0' and @type = 'date']</value>
      <webElementGuid>2af3f907-2806-4a90-baf8-1dcef6423b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
