<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NgayVe</name>
   <tag></tag>
   <elementGuidId>d2568474-bb45-408b-8d48-1fce57f57ab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='schedule-ret-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#schedule-ret-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#schedule-ret-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8003f61b-a88c-4a8f-9ebf-295cff9e96f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>schedule-ret-0</value>
      <webElementGuid>6f3c5083-2ff6-4599-8565-023a427045ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border border-outline-variant rounded-lg text-xs focus:outline-none</value>
      <webElementGuid>0b109783-3297-41e5-a3f7-283dea66eabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>51dd49de-f75e-418f-a7ef-31079a99cb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;schedule-ret-0&quot;)</value>
      <webElementGuid>898bef85-1104-4faf-a68c-6f189ce6b925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='schedule-ret-0']</value>
      <webElementGuid>e682b121-2cc5-4833-a55c-8a766d09b9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/section[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>c5b3de52-6145-4540-a597-1b5fe70e87ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>28ce7c17-a37a-4f83-adb4-e4254c229789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'schedule-ret-0' and @type = 'date']</value>
      <webElementGuid>7b9782f0-18df-480c-864f-bc2dd404388a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
